name:                httpbin
version:             0.1.0.0
description:         A simple httpbin clone in Haskell

dependencies:
- base >= 4.7 && < 5
- wai
- warp
- http-types
- bytestring
- aeson
- aeson-pretty
- wai-extra
- case-insensitive
- network
- text

executables:
  httpbin:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N